In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/hr_data.csv')

In [4]:
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  object
 8   salary                 14999 non-null  object
dtypes: int64(7), object(2)
memory usage: 1.0+ MB

In [11]:
df['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [15]:
df[df['department']=='IT']

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [15]:
df[df['department']=='IT']

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [19]:
df[df['department']=='IT']['number_project'].sum()

np.int64(4683)

In [18]:
df[df['department']=='RandD']

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
301,2847,3,278,4,0,1,0,RandD,medium
302,57006,7,250,5,0,1,0,RandD,medium
303,2880,2,127,3,0,1,0,RandD,medium
304,2881,5,255,5,0,1,0,RandD,medium
305,2882,2,135,3,0,1,0,RandD,medium
...,...,...,...,...,...,...,...,...,...
14939,87333,4,273,5,0,1,0,RandD,medium
14940,87335,5,285,4,1,1,0,RandD,medium
14941,87339,2,131,3,0,1,0,RandD,high
14942,87341,5,135,6,0,1,0,RandD,low
14943,96411,5,239,5,0,1,0,RandD,medium

In [17]:
df[df['department']=='RandD'].sum()

employee_id                                                       32948168
number_project                                                        3033
average_montly_hours                                                158030
time_spend_company                                                    2650
Work_accident                                                          134
left                                                                   121
promotion_last_5years                                                   27
department               RandDRandDRandDRandDRandDRandDRandDRandDRandDR...
salary                   mediummediummediummediummediummediummediummedi...
dtype: object

In [20]:
df[df['department']=='RandD']['number_project'].sum()

np.int64(3033)

In [24]:
df.groupby('department').count()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,salary
department,,,,,,,,
IT,1227,1227,1227,1227,1227,1227,1227,1227
RandD,787,787,787,787,787,787,787,787
accounting,767,767,767,767,767,767,767,767
hr,739,739,739,739,739,739,739,739
management,630,630,630,630,630,630,630,630
marketing,858,858,858,858,858,858,858,858
product_mng,902,902,902,902,902,902,902,902
sales,4140,4140,4140,4140,4140,4140,4140,4140
support,2229,2229,2229,2229,2229,2229,2229,2229
technical,2720,2720,2720,2720,2720,2720,2720,2720

##### **Group By Questions**

##### 1. Group by department and find the average mothly hours of employees in each department.

In [35]:
df.groupby(['department'])['average_montly_hours'].sum()

department
IT             248119
RandD          158030
accounting     154292
hr             146828
management     126787
marketing      171073
product_mng    180369
sales          831773
support        447490
technical      550793
Name: average_montly_hours, dtype: int64

##### 2.Group by department and calculate the total number of employees in each department.

In [34]:
df.groupby(['department'])['employee_id'].count()

department
IT             1227
RandD           787
accounting      767
hr              739
management      630
marketing       858
product_mng     902
sales          4140
support        2229
technical      2720
Name: employee_id, dtype: int64

##### 3.Group by number_project and find the average time spent in the company

In [45]:
df.groupby(['number_project'])['time_spend_company'].mean()

number_project
2    3.180486
3    3.286560
4    3.454983
5    3.800072
6    4.192504
7    4.113281
Name: time_spend_company, dtype: float64

##### 4.Group by department and compute : average monthly  hours average number of projects.

In [50]:
df.groupby('department')[['average_montly_hours','number_project']].mean()

             average_montly_hours  number_project
department
IT                     202.215974        3.816626
RandD                  200.800508        3.853875
accounting             201.162973        3.825293
hr                     198.684709        3.654939
management             201.249206        3.860317
marketing              199.385781        3.687646
product_mng            199.965632        3.807095
sales                  200.911353        3.776329
support                200.758188        3.803948
technical              202.497426        3.877941

##### 5.Group by left and find : average monthly hours average time spent in the company.

In [51]:
df.groupby('left')[['average_montly_hours','time_spend_company']].mean()

      average_montly_hours  time_spend_company
left
0               199.060203            3.380032
1               207.419210            3.876505

##### 6.Group by department and left, then find the average monthly hours

In [52]:
df.groupby(['department','left'])['average_montly_hours'].count()

department   left
IT           0        954
             1        273
RandD        0        666
             1        121
accounting   0        563
             1        204
hr           0        524
             1        215
management   0        539
             1         91
marketing    0        655
             1        203
product_mng  0        704
             1        198
sales        0       3126
             1       1014
support      0       1674
             1        555
technical    0       2023
             1        697
Name: average_montly_hours, dtype: int64

##### 7.Group by number_project and promotion_last_5Years, then calculate the employee count.

In [53]:
df.groupby(['number_project','promotion_last_5years'])['employee_id'].count()

number_project  promotion_last_5years
2               0                        2351
                1                          37
3               0                        3960
                1                          95
4               0                        4248
                1                         117
5               0                        2711
                1                          50
6               0                        1154
                1                          20
7               0                         256
Name: employee_id, dtype: int64

##### 8. Group by department and work_accident, then find the average time spent in the company.

##### 9.Group by department and calculate multiple aggrigations : mean of the average_monthly_hours max of time _spend_company sum of work_accident.

##### 10.Group by department and left, then use agg() to compute : average monthly hours minimum and maximum number of projects count of employees.

##### **Amazon data set**

In [8]:
import pandas as pd
import numpy as np
amazon_df=pd.read_csv('amazon_fires (1).csv',encoding='ISO-8859-1')

In [9]:
amazon_df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

##### 1. Number of employees who got fired in the month of january.

##### 2.Number of people who got fired in 2002(need features enhgineering)

##### 3. Number of fires in year 2001 in Tocantins

##### **Titanic data set**

In [20]:
import pandas as pd
import numpy as np
df=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/titanic.csv')

In [21]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

##### 1.How many peoples are survived in b5 cabin

In [26]:
df=df.groupby('cabin')['survived'].sum().get('B5')

AttributeError: 'SeriesGroupBy' object has no attribute 'groupby'

In [23]:
df.groupby('cabin')['B5'].count()

AttributeError: 'SeriesGroupBy' object has no attribute 'groupby'

##### 2.count of females whose age is less than 20 and survived

In [16]:
df.groupby(df[df['sex'=='fe])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (1124366432.py, line 1)

##### 3.Total fare paid by embarked S females.

##### 4.count of ppl in pclass 3 having only 1 person with them

##### 5.maximum fare paid in embarked Q

##### **HR Data set**

##### 1.Avg time spend by the ppl in support department who got promoted